# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve/CMakeFiles /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve/CMakeFiles /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/halin/Northwestern_University/2025_Summer/gap-4.14.0/pkg/ve/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ve_kernel

# Build rule for target.
ve_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ve_kernel
.PHONY : ve_kernel

# fast build rule for target.
ve_kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve_kernel.dir/build.make CMakeFiles/ve_kernel.dir/build
.PHONY : ve_kernel/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named report

# Build rule for target.
report: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 report
.PHONY : report

# fast build rule for target.
report/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report.dir/build.make CMakeFiles/report.dir/build
.PHONY : report/fast

#=============================================================================
# Target rules for targets named distrib

# Build rule for target.
distrib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distrib
.PHONY : distrib

# fast build rule for target.
distrib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distrib.dir/build.make CMakeFiles/distrib.dir/build
.PHONY : distrib/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f src/int/CMakeFiles/parser.dir/build.make src/int/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named zme

# Build rule for target.
zme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zme
.PHONY : zme

# fast build rule for target.
zme/fast:
	$(MAKE) $(MAKESILENT) -f src/int/CMakeFiles/zme.dir/build.make src/int/CMakeFiles/zme.dir/build
.PHONY : zme/fast

#=============================================================================
# Target rules for targets named parser_rat

# Build rule for target.
parser_rat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser_rat
.PHONY : parser_rat

# fast build rule for target.
parser_rat/fast:
	$(MAKE) $(MAKESILENT) -f src/rat/CMakeFiles/parser_rat.dir/build.make src/rat/CMakeFiles/parser_rat.dir/build
.PHONY : parser_rat/fast

#=============================================================================
# Target rules for targets named qme

# Build rule for target.
qme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qme
.PHONY : qme

# fast build rule for target.
qme/fast:
	$(MAKE) $(MAKESILENT) -f src/rat/CMakeFiles/qme.dir/build.make src/rat/CMakeFiles/qme.dir/build
.PHONY : qme/fast

#=============================================================================
# Target rules for targets named me

# Build rule for target.
me: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 me
.PHONY : me

# fast build rule for target.
me/fast:
	$(MAKE) $(MAKESILENT) -f src/ve/CMakeFiles/me.dir/build.make src/ve/CMakeFiles/me.dir/build
.PHONY : me/fast

src/ve.o: src/ve.cc.o
.PHONY : src/ve.o

# target to build an object file
src/ve.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve_kernel.dir/build.make CMakeFiles/ve_kernel.dir/src/ve.cc.o
.PHONY : src/ve.cc.o

src/ve.i: src/ve.cc.i
.PHONY : src/ve.i

# target to preprocess a source file
src/ve.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve_kernel.dir/build.make CMakeFiles/ve_kernel.dir/src/ve.cc.i
.PHONY : src/ve.cc.i

src/ve.s: src/ve.cc.s
.PHONY : src/ve.s

# target to generate assembly for a file
src/ve.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ve_kernel.dir/build.make CMakeFiles/ve_kernel.dir/src/ve.cc.s
.PHONY : src/ve.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... distrib"
	@echo "... parser"
	@echo "... parser_rat"
	@echo "... report"
	@echo "... me"
	@echo "... qme"
	@echo "... ve_kernel"
	@echo "... zme"
	@echo "... src/ve.o"
	@echo "... src/ve.i"
	@echo "... src/ve.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

